# Generated by Django 5.0 on 2023-12-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_item_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.FloatField(default=0, null=True),
        ),
    ]
